### ISSUE TITLE
Downloading stops when unfocused.

### ISSUE THREAD

**Issue by Rockster34** [Alaanor/beatlist#33]
The downloads from playlists/OCI's will stop once you stop focusing on the beatlist app making it insanely tedious and making it take longer to bulk download.

Downloads in turn also stop when you have too many at the same time and you have to reset the app to fix this issue.

**Comment by Alaanor** [comment]
I saw it. It's fixed for the next version 👍

**Comment by Alaanor** [comment]
Tbh I'm unsure what was the real cause of this but I don't think this issue is valid anymore with the 1.2.0. I just tried to launch 150 download withtout the app being focused and this just went fine.

I'm closing the issue now that 1.2 got released but if you still have this problem, don't hesitate to re-open the issue.
