### ISSUE TITLE
Duplicate Handling

### ISSUE THREAD

**Issue by livejamie** [Alaanor/beatlist#34]
I have some issues with my library in having duplicate songs, but Beatlist thinks it's just one song.

Example:
![image](https://user-images.githubusercontent.com/49513/80038288-34997380-84aa-11ea-92a3-ffcb800eb29a.png)

I don't know which directory to delete without losing my local scores.

**Comment by Alaanor** [comment]
Mhhh interesting. I would say that's kinda a good way to handle it the behaviour right now. To see which one is it, you could click on it and click on the folder button to open the exact folder is it using.

Concerning score you shouldn't loose anything as it's all on scoresaber anyway. You may loose your local score on your pc but you're still on the leaderboard of scoresaber. It happened me multiple time to reinstall all and I don't loose any score as they're all on scoresaber.

For the duplicate, I'm unsure what behaviour for the program should be the best ? To ignore it like now ?

**Comment by Alaanor** [comment]
I made some thinking and I think to handle duplicate beatmap in another way is a workaround instead of a fix. The reason is that it shouldn't have happened in first place, to have 2 same song.

Maybe beatlist ignored one of those because it's an invalid one. Hence why you were able to download it a second time, that would be the right behaviour. One way to validate this hypothesis is to check what is being loaded in game, is there 2 time the same map ?

**Comment by livejamie** [comment]
Yes it's the exact same map just different folder names.

**Comment by Alaanor** [comment]
> I made some thinking and I think to handle duplicate beatmap in another way is a workaround instead of a fix. The reason is that it shouldn't have happened in first place, to have 2 same song.

Closing this issue as wont-fix. At the moment, I think it's beyond the goal of beatlist. But I'm still open to do something if some people show interest in this issue.
