### ISSUE TITLE
Colon (:) not included in filename replace characters

### ISSUE THREAD

**Issue by b-rad15** [Alaanor/beatlist#35]
Songs with a Colon (:) cause an error because they are invalid file characters on windows
Just change line 90 of src/lib/BeatSaber.ts from`      .replace(/[|&;$%@"<>()+,]/g, '')` to `      .replace(/[|&;$%@"<>()+,:]/g, '')` and it should fix it

**Comment by b-rad15** [comment]
fixed in #36

**Comment by Alaanor** [comment]
Arf I feel bad because I don't mention it in the readme, but you did not see the develop branch which is like 250 commit ahead master. The edit is already done as you can see here:
https://github.com/Alaanor/beatlist/blob/6fe7c4c2b2a954cb7f35775e5d0b5afbb85a135f/src/libraries/os/beatSaber/BeatSaber.ts#L61

**Comment by Alaanor** [comment]
I'll merge it since it indeed fix a problem. But I wont release something from the master content, next release is with develop. Thanks for the PR tho, I appreciate the effort ;) the develop has to be updated with master anyway.
