### ISSUE TITLE
Add ability to edit rename song details within beatlist

### ISSUE THREAD

**Issue by ANewDawn** [Alaanor/beatlist#48]
Some songs have long names and/or misspelled.

Be nice be able to rename song details (song name, artist) etc within beatlist

**Comment by Alaanor** [comment]
That's out of the scope of beatlist nor I have the possibility to implement it unfortunately.

The reason is that I'm using beatsaver as source, so data are from there. A local edit would change the hash of the map and therefore invalidate the leaderboard (I don't know whatever scoresaber would create a new leaderboard or just refuse, but in any case it's not a behavior we want).

**Comment by ANewDawn** [comment]
That makes sense thanks for info
