### ISSUE TITLE
Beatmap folder creation failed

### ISSUE THREAD

**Issue by MaverickMartyn** [Alaanor/beatlist#66]
When attempting to download this song (https://beatsaver.com/beatmap/74d5) I get the following error:
"Error: Error: Couldn't create a folder for the new beatmap."
I assume this has to do with the title needing further sanitization, as it contains a question mark, which is an illegal character for Windows filenames.
Downloading it manually from Beatsaver and extracting it to a folder with the same naming convention, minus the question mark worked fine.

**Comment by Alaanor** [comment]
#37, #35, #20 are all about this error, but this should have been fixed by now. I just tried with the one installed on my pc, it just downloaded fine.

Could you please ensure you're in 1.2.1, the latest version ? It is written on the home page, below the logo. I just want to ensure that before going further :). There's no auto-update for beatlist.

**Comment by MaverickMartyn** [comment]
Ah. Sorry. Must have missed those issues in my quick search.
I see I am running 1.1.4. I just assumed it would auto update. My mistake. :)
(Speaking of, is such a feature planned?)

**Comment by Alaanor** [comment]
No problem, glad it was not a new bug lol

It is in the roadmap but who knows when I'll code it. At the moment I'm more in a maintenance mode rather than adding new functionality. But I might get motivation again :)

**Comment by MaverickMartyn** [comment]
I might take a look at the project one of these days.
With it being Electron, with Vue and TypeScript, it wouldn't be my first rodeo.
