### ISSUE TITLE
Support case sensitive file systems

### ISSUE THREAD

**Issue by 9cxndy** [Alaanor/beatlist#69]
Looks like beatlist converts all paths to lower case. This doesn't work on, for example, Linux, which has case sensitive file systems

**Comment by Alaanor** [comment]
Even tho I'm a Arch Linux user myself, I do game on windows and I made it to support windows. The reason I did not even try to support linux is because I dont have the time, personally, to test on both platform nor I game on linux (got an nvidia gpu). The readme.md specify that only windows is supported.

I had problem in the past for case insensitive path when comparing two path which pointed on the same location for the OS but did not pass the === string equals. So my quick and dirty solution at this time was to lowercase them all.

But if you got the time to test and make it working, I'd be glad to accept PR about this 👍

**Comment by Alaanor** [comment]
I'll close at wont-fix for now, but know that I'm open to PR
