### ISSUE TITLE
Request to add 'search by difficulty' option

### ISSUE THREAD

**Issue by DanP27** [Alaanor/beatlist#7]
I would like to be able to not only search by keyword but also the difficulties the song is mapped too if possible, please.

**Comment by Alaanor** [comment]
The feature is already implemented in [feature-beatsaver-integration](https://github.com/Alaanor/beatlist/tree/feature-beatsaver-integration) branch which I'm currently working on. Hence, it will be available on the next release. 👍 
I can't give a release date since I'm working on it on my free time :/ But it is definitively something that will be implemented as it is already done there.

**Comment by Alaanor** [comment]
![image](https://user-images.githubusercontent.com/8039130/66272273-cb347900-e867-11e9-8f60-d133025e4181.png)
It is now available in the latest version ! (https://github.com/Alaanor/beatlist/releases/tag/v1.1.0)

**Comment by Alaanor** [comment]
I can now close this issue.
